In [1]:
import numpy as np

1. Create a 1D array of numbers from 0 to 9

In [6]:
array = np.arange(0, 10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


2. Create a 3×3 NumPy array of all Boolean value Trues

In [16]:
array = np.ones(9, dtype=bool).reshape(3, 3)

print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


3. Extract all odd numbers from array of 1-10

In [23]:
array = np.arange(10)
print(array[array%2==1])

[1 3 5 7 9]


4. Replace all odd numbers in an array of 1-10 with the value -1

In [25]:
array = np.arange(10)
array[array%2==1] = -1

print(array)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


5. Convert a 1D array to a 2D array with 2 rows

In [34]:
array = np.arange(4).reshape(2,2)
print(array)

[[0 1]
 [2 3]]


6. Create two arrays a and b, stack these two arrays vertically use the np. np.sum to calculate totals

In [37]:
a = np.arange(1, 5)
b = np.arange(1, 5)

c = np.dot(a, b)
sum = np.sum(c)
print(sum)

30


<font color=yellow><b><center>EXTENSION</b></center></font>

1. Create the following pattern without hardcoding. Use only NumPy functions.

2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b 3. Get all items between 3 and 7 from a and b and sum them together

3. Get all items between 3 and 7 from a and b and sum them together